In [21]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'c1':[11,21,np.nan],'c2':[12, np.nan, np.nan],'c3':[13, 23, 33]})
print(df)

     c1    c2  c3
0  11.0  12.0  13
1  21.0   NaN  23
2   NaN   NaN  33

In [22]:
df.isna() #boolean function

      c1     c2     c3
0  False  False  False
1  False   True  False
2   True   True  False

In [23]:
df.notna() #boolean function

      c1     c2    c3
0   True   True  True
1   True  False  True
2  False  False  True

In [24]:
df.isna().sum() #to count the number of missing values in each column

c1    1
c2    2
c3    0
dtype: int64

In [25]:
df.dropna() #to drop the rows with missing values

     c1    c2  c3
0  11.0  12.0  13

In [26]:
df.fillna(value='DEFAULT')

        c1       c2  c3
0     11.0     12.0  13
1     21.0  DEFAULT  23
2  DEFAULT  DEFAULT  33

In [27]:
df.fillna(df.mean()) #mean values of columns are calculated

     c1    c2  c3
0  11.0  12.0  13
1  21.0  12.0  23
2  16.0  12.0  33

In [28]:
import pandas as pd

data = {
    'Roll no' : [454,456,457,458,459],
    'Name' : ['Akshat', 'Max', 'Charles', 'Enzo', 'Michael'],
    'Age' : [23, 25, '-', 21, 29],
    'Marks' : [85, 90, 91, '-', 75],
    'Department' : ['CSE', 'Entc', 'IT', 'AIML', 'cse'],
    'Admission_Date': ['1/6/24', '3/6/24','5/6/24', '6/6/24','7-6-24']

}

df = pd.DataFrame(data)
df

   Roll no     Name Age Marks Department Admission_Date
0      454   Akshat  23    85        CSE         1/6/24
1      456      Max  25    90       Entc         3/6/24
2      457  Charles   -    91         IT         5/6/24
3      458     Enzo  21     -       AIML         6/6/24
4      459  Michael  29    75        cse         7-6-24

In [29]:
# Step 2: Replace '-'  with NaN to mark missing values

df.replace('-', np.nan, inplace=True)

# Convert columns to numeric where needed

df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
df['Marks'] = pd.to_numeric(df['Marks'], errors='coerce')

/tmp/ipykernel_972/2291458035.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace('-', np.nan, inplace=True)

In [30]:
# Step 3: Check missing values

print('\nMissing values: ')
print(df.isnull().sum())

Missing values:
Roll no           0
Name              0
Age               1
Marks             1
Department        0
Admission_Date    0
dtype: int64

In [31]:
# Fill missing age with mean

df['Age'].fillna(df['Age'].mean(), inplace=True)

# Fill missing marks with median

df['Marks'].fillna(df['Marks'].median(), inplace=True)
df

/tmp/ipykernel_972/2467888530.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)
/tmp/ipykernel_972/2467888530.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Marks'].fillna(df['Marks'].median(), inplace=True)

   Roll no     Name   Age  Marks Department Admission_Date
0      454   Akshat  23.0   85.0        CSE         1/6/24
1      456      Max  25.0   90.0       Entc         3/6/24
2      457  Charles  24.5   91.0         IT         5/6/24
3      458     Enzo  21.0   87.5       AIML         6/6/24
4      459  Michael  29.0   75.0        cse         7-6-24

In [32]:
# Step 5: Fix inconsistent text formatting

df['Department'] = df['Department'].str.upper()
df

   Roll no     Name   Age  Marks Department Admission_Date
0      454   Akshat  23.0   85.0        CSE         1/6/24
1      456      Max  25.0   90.0       ENTC         3/6/24
2      457  Charles  24.5   91.0         IT         5/6/24
3      458     Enzo  21.0   87.5       AIML         6/6/24
4      459  Michael  29.0   75.0        CSE         7-6-24

In [33]:
# Step 6: Convert admission_date to standard datetime format

df['Admission_Date'] = pd.to_datetime(df['Admission_Date'], errors='coerce')
df

/tmp/ipykernel_972/2653541783.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Admission_Date'] = pd.to_datetime(df['Admission_Date'], errors='coerce')

   Roll no     Name   Age  Marks Department Admission_Date
0      454   Akshat  23.0   85.0        CSE     2024-01-06
1      456      Max  25.0   90.0       ENTC     2024-03-06
2      457  Charles  24.5   91.0         IT     2024-05-06
3      458     Enzo  21.0   87.5       AIML     2024-06-06
4      459  Michael  29.0   75.0        CSE     2024-07-06

In [34]:
# Step 7: Show cleaned data
print('\nCleaned data: ')
df

Cleaned data:

   Roll no     Name   Age  Marks Department Admission_Date
0      454   Akshat  23.0   85.0        CSE     2024-01-06
1      456      Max  25.0   90.0       ENTC     2024-03-06
2      457  Charles  24.5   91.0         IT     2024-05-06
3      458     Enzo  21.0   87.5       AIML     2024-06-06
4      459  Michael  29.0   75.0        CSE     2024-07-06

In [35]:
# Step 8: Save cleaned dataset
df.to_csv('cleaned_student_data.csv', index=False)

print('\nCleaned CSV file saved as cleaned_student_data.csv')

Cleaned CSV file saved as cleaned_student_data.csv

In [36]:
# Commands on cars93:

import pandas as pd
import numpy as np
df = pd.read_csv('/content/Cars93 (1).csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [37]:
df['Luggage.room'].median()

14.0

In [39]:
df = pd.read_csv('/content/Cars93 (1).csv')
df.isna().sum()
df['Luggage.room']=df['Luggage.room'].fillna(value=df['Luggage.room'].mean())
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.000000
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.000000
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.000000
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.000000
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.000000
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,13.890244
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.000000
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.000000
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.000000
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.000000

In [40]:
df.head

<bound method NDFrame.head of    Manufacturer    Model     Type  Price  MPG.city             AirBags  \
0         Acura  Integra    Small   15.9        25                 NaN
1         Acura   Legend  Midsize   33.9        18  Driver & Passenger
2          Audi       90  Compact   29.1        20         Driver only
3          Audi      100  Midsize   37.7        19  Driver & Passenger
4           BMW     535i  Midsize   30.0        22         Driver only
..          ...      ...      ...    ...       ...                 ...
88   Volkswagen  Eurovan      Van   19.7        17                 NaN
89   Volkswagen   Passat  Compact   20.0        21                 NaN
90   Volkswagen  Corrado   Sporty   23.3        18                 NaN
91        Volvo      240  Compact   22.7        21         Driver only
92        Volvo      850  Midsize   26.7        20  Driver & Passenger

    Horsepower  Passengers  Rear.seat.room  Luggage.room
0          140           5            26.5     11.000000
1          200           5            30.0     15.000000
2          172           5            28.0     14.000000
3          172           6            31.0     17.000000
4          208           4            27.0     13.000000
..         ...         ...             ...           ...
88         109           7            34.0     13.890244
89         134           5            31.5     14.000000
90         178           4            26.0     15.000000
91         114           5            29.5     14.000000
92         168           5            30.0     15.000000

[93 rows x 10 columns]>

In [41]:
df['Rear.seat.room']=df['Rear.seat.room'].fillna(value=df['Rear.seat.room'].median())
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.000000
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.000000
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.000000
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.000000
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.000000
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,13.890244
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.000000
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.000000
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.000000
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.000000

In [42]:
df.to_csv('cleaned_cars93.csv', index=False)

print('\nCleaned CSV file saved as cleaned_cars93.csv')

Cleaned CSV file saved as cleaned_cars93.csv